#!/usr/bin/env bash
set -euo pipefail

# This script is generated by modules/sd-card/sd-image-armbian.nix.
# It takes an Armbian source image and produces a hybrid image whose
# bootloader/partition layout comes from Armbian but whose /boot and /
# contents come from a NixOS build.
#
# Environment variables set by the Nix derivation:
#   BOOT_FILES    directory with Image, initrd, uInitrd, dtb, armbianEnv.txt
#   ROOTFS_IMAGE  path to the NixOS rootfs ext4 image

SOURCE_IMAGE="${SOURCE_IMAGE:-@defaultSourceImage@}"
OUTPUT_IMAGE="${OUTPUT_IMAGE:-}"

usage() {
  cat <<EOF
Usage: $0 --source-image <armbian.img> --output <output.img>

Environment overrides:
  SOURCE_IMAGE    path to the source Armbian image (default from Nix config or --source-image)
  OUTPUT_IMAGE    path where the hybrid image will be written
  BOOT_FILES      @bootFiles@
  ROOTFS_IMAGE    @rootfsImage@
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-image)
      SOURCE_IMAGE="$2"
      shift 2
      ;;
    --output)
      OUTPUT_IMAGE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      ;;
  esac
done

BOOT_FILES="${BOOT_FILES:-@bootFiles@}"
ROOTFS_IMAGE="${ROOTFS_IMAGE:-@rootfsImage@}"

if [[ -z "$SOURCE_IMAGE" || -z "$OUTPUT_IMAGE" ]]; then
  echo "ERROR: --source-image and --output are required."
  usage
fi

if [[ ! -f "$SOURCE_IMAGE" ]]; then
  echo "ERROR: source image not found: $SOURCE_IMAGE"
  exit 1
fi

echo "Creating output image from source..."
cp -f "$SOURCE_IMAGE" "$OUTPUT_IMAGE"

# Expand the output image so the NixOS rootfs (typically > 1.7 GiB) fits.
# The Armbian source image is usually ~2 GiB; we grow it to 4 GiB and extend
# the root partition to fill the new space.
TARGET_SIZE="${TARGET_SIZE:-4G}"
echo "Expanding output image to $TARGET_SIZE..."
truncate -s "$TARGET_SIZE" "$OUTPUT_IMAGE"

# Relocate the GPT backup header to the new end of the image, then grow the
# root partition (partition 2) to use all remaining space.
echo "Growing root partition..."
sudo @sfdisk@ --relocate gpt-bak-std "$OUTPUT_IMAGE" <<< ""
echo ",+" | sudo @sfdisk@ -N 2 --no-reread "$OUTPUT_IMAGE"

# Create temporary mount points.
WORK_DIR=$(mktemp -d)
BOOT_MNT="$WORK_DIR/boot"
ROOT_MNT="$WORK_DIR/root"
mkdir -p "$BOOT_MNT" "$ROOT_MNT"

# Attach the image to a fresh loop device with partition scanning enabled.
LOOP_DEV=$(sudo losetup -f --show -P "$OUTPUT_IMAGE")

if [[ -z "$LOOP_DEV" ]]; then
  echo "ERROR: failed to attach loop device"
  rm -rf "$WORK_DIR"
  exit 1
fi

cleanup() {
  sudo umount -R "$BOOT_MNT" "$ROOT_MNT" 2>/dev/null || true
  [[ -n "${LOOP_DEV:-}" ]] && sudo losetup -d "$LOOP_DEV" 2>/dev/null || true
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

echo "Using loop device: $LOOP_DEV"

# Mount boot partition (p1) and root partition (p2).
sudo mount "${LOOP_DEV}p1" "$BOOT_MNT"
sudo mount "${LOOP_DEV}p2" "$ROOT_MNT"

# Replace boot partition contents while keeping Armbian's boot.cmd/boot.scr
# and other firmware files intact.  We only overwrite the kernel, initrd,
# dtb and environment files generated by the NixOS build.
echo "Populating boot partition..."
# Remove the old kernel, initrd, dtb and their versioned counterparts.
# Armbian keeps these as real files with symlinks pointing at them, so we
# must remove both the symlinks and the targets.
sudo rm -f "$BOOT_MNT"/Image "$BOOT_MNT"/vmlinuz-*
sudo rm -f "$BOOT_MNT"/uInitrd "$BOOT_MNT"/uInitrd-*
sudo rm -f "$BOOT_MNT"/initrd.img "$BOOT_MNT"/initrd.img-*
sudo rm -rf "$BOOT_MNT"/dtb "$BOOT_MNT"/dtb-*
sudo rm -f "$BOOT_MNT"/System.map-* "$BOOT_MNT"/config-*
sudo rm -f "$BOOT_MNT"/armbianEnv.txt

sudo cp -r "$BOOT_FILES"/* "$BOOT_MNT/"
sudo chown -R root:root "$BOOT_MNT"

# Replace root filesystem.
echo "Writing NixOS rootfs..."
sudo umount "$ROOT_MNT"
sudo dd if="$ROOTFS_IMAGE" of="${LOOP_DEV}p2" bs=4M status=progress conv=fsync

# The rootfs image is sized to its contents; expand it to fill the partition.
echo "Resizing root filesystem..."
sudo @e2fsck@ -f -p "${LOOP_DEV}p2" || true
sudo @resize2fs@ "${LOOP_DEV}p2"

# Ensure boot partition label is what Armbian's boot.cmd expects, and the
# root partition is labelled NIXOS_SD so both armbianEnv.txt and the
# running NixOS system can find it.
echo "Labelling partitions..."
sudo @e2label@ "${LOOP_DEV}p1" armbi_boot
sudo @e2label@ "${LOOP_DEV}p2" NIXOS_SD

# Force sync before detach.
sync

echo "Done: $OUTPUT_IMAGE"
